[build]
  command = "npm run build"
  publish = "build"

# Handle React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the server in development
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200